### ISSUE TITLE
Very long excerpts in concordance

### ISSUE THREAD

**Issue by clovis** [ARTFL-Project/PhiloLogic4#324]
This can be seen in new Frantext builds when searching for "longtemps couché bonheur" in the same sentence on page 2. 

See <a href="http://condorcet.uchicago.edu/philologic4/frantext_demo/dispatcher.py?year_interval=10&word_num=5&end=40&end_date=&arg_phrase=&title=&author=&arg_proxy=&start=26&method=cooc&q=longtemps+couch%C3%A9+bonheur&report=concordance&results_per_page=25&filter_frequency=100&arg=6&date=&colloc_filter_choice=frequency&start_date=&text_genre=">here</a> if still up:

**Comment by rwhaling** [comment]
This is happening because the core is returning much larger results than it
should.  No need to cap result length at the display side.

Not sure if the weird results are a parser problem, or getting wrong
parameters to search core.
Rw

**Comment by clovis** [comment]
Right... I'm still going to leave this open for future reference. If only to parse this file individually to see what going on...

**Comment by clovis** [comment]
No longer happens with new code... Probably a misconfiguration at load time.
