### ISSUE TITLE
Crash when searching for phrases in quotes

### ISSUE THREAD

**Issue by clovis** [ARTFL-Project/PhiloLogic4#325]
It seems that all searches with quotes die in latest builds.

<a href="http://pantagruel.ci.uchicago.edu/philologic4/theatre_notes/dispatcher.py/?report=concordance&q=mon+amour&method=proxy&arg_proxy=&arg_phrase=&author=&title=&author_dates=&date=&publisher=&pub_place=&pub_date=&extent=&editor=&identifiers=&text_genre=&keywords=&language=&notes=&auth_gender=&collection=&period=&text_form=&structure=&filename=&options=&head=&type=&n=&id=&act=&scene=&who=&word_num=5&filter_frequency=100&colloc_filter_choice=frequency&start_date=&end_date=&year_interval=10&results_per_page=25">This query</a> works, while  <a href="http://pantagruel.ci.uchicago.edu/philologic4/theatre_notes/dispatcher.py/?report=error&q=%22mon+amour%22&method=proxy&arg_proxy=&arg_phrase=&author=&title=&author_dates=&date=&publisher=&pub_place=&pub_date=&extent=&editor=&identifiers=&text_genre=&keywords=&language=&notes=&auth_gender=&collection=&period=&text_form=&structure=&filename=&options=&head=&type=&n=&id=&act=&scene=&who=&word_num=5&filter_frequency=100&colloc_filter_choice=frequency&start_date=&end_date=&year_interval=10&results_per_page=25&error_report=concordance">the same query with quotes</a> fails. Note that the cache needs to be cleared as the quoted search dies initially because of a CGI timeout, most likely indicating, *I think*, a search core issue.

**Comment by rwhaling** [comment]
Can you do me a favor and confirm that this bug occurs on both Linux and
Mac?  I will fix it as I merge in the new core late next week.
Rw
