### ISSUE TITLE
corpus_search binary hanging on flexible matching

### ISSUE THREAD

**Issue by clovis** [ARTFL-Project/PhiloLogic4#360]
I noticed that the new core hangs when searching for he.* in the Frantext database.

Same thing actually happens with the old core, though this time it's the Python interpreter hanging.

I checked on the philo3 database with hE* and it works.

**Comment by rwhaling** [comment]
I believe I have fixed this as of my most recent commit:
https://github.com/rwhaling/PhiloLogic4/commit/d04bf379b1c089aee654ec412071d55afb7b125e
Would you mind testing, and if possible, confirming that it's not breaking some other things?
