### ISSUE TITLE
breadcrumbs not tracking successive facet interactions

### ISSUE THREAD

**Issue by rwhaling** [ARTFL-Project/PhiloLogic4#373]
The metadata-facet selection "breadcrumbs", as well as the search form, are failing to accumulate values after the first facet selection.  To reproduce:
Look at:
http://pantagruel.ci.uchicago.edu/philologic4/strauss_9/
search for "power"
facet on course title, select the first, seminar on montesquieu,
facet on session, select the first, session 10
you will note there is no breadcrumb for session 10, nor is it visible in the search form, yet it is reflected in the search parameters, and it is impossible to clear out the session 10 parameter from the query via the UI.

**Comment by rwhaling** [comment]
Upon reflection, I suspect this is happening because "session" is a compound facet, on ["course","n"], while "n" is itself configured not to be a facet.

**Comment by rwhaling** [comment]
Confirmed, adding session number to the search form fixes this.  interesting behavior, not sure if this should be considered a bug or not.

**Comment by clovis** [comment]
I don't think it's a bug since the code is working as intented. See [here](https://github.com/ARTFL-Project/PhiloLogic4/blob/master/www/app/shared/searchArguments/searchArgumentsDirective.js#L20). However, I do think the breadcrumbs shouldn't be limited to displaying what's available in the search form. I'll work on a fix ASAP.

**Comment by clovis** [comment]
I believe this is fixed. I've changed the way I build the breadcrumbs, and now iterate over query arguments, and check if either of them is in the search form or in a facet. See [here](https://github.com/ARTFL-Project/PhiloLogic4/blob/master/www%2Fapp%2Fshared%2FsearchArguments%2FsearchArgumentsDirective.js#L21).

I've updated the strauss_9 db with the new code, and removed "n" from the search form. The following query now works:
http://pantagruel.ci.uchicago.edu/philologic4/strauss_9/query?year_interval=10&word_num=5&frequency_field=&end=0&script=&title=%22Seminar%20on%20Montesquieu%22&n=%2210%22&q=power&start=0&filter_frequency=100&arg=&report=concordance&colloc_filter_choice=frequency&philo_type=&method=proxy
