### ISSUE TITLE
Mac osx (Sierra) install

### ISSUE THREAD

**Issue by AlexandreGefen** [ARTFL-Project/PhiloLogic4#522]
Hello,
I've read OS X no longer supported but any idea to solve this issue when running Philoload ?

Traceback (most recent call last):
  File "/usr/local/bin/philoload4", line 9, in <module>
    from philologic.LoadOptions import LoadOptions
  File "/Library/Python/2.7/site-packages/philologic/__init__.py", line 5, in <module>
    from .DB import DB
  File "/Library/Python/2.7/site-packages/philologic/DB.py", line 5, in <module>
    from .Config import Config, db_locals_defaults, db_locals_header
  File "/Library/Python/2.7/site-packages/philologic/Config.py", line 7, in <module>
    from philologic.utils import pretty_print
  File "/Library/Python/2.7/site-packages/philologic/utils/__init__.py", line 5, in <module>
    from .convert_entities import convert_entities
  File "/Library/Python/2.7/site-packages/philologic/utils/convert_entities.py", line 4, in <module>
    import six.moves.html_entities
ImportError: No module named html_entities

thanks !
Alexandre

NB Philologic 4.1 runs perfectly on the same computer

**Comment by clovis** [comment]
Hi Alexandre,

Sorry for the late response... I believe you may have been running the master branch which is really our development branch. You were probably running into a Python2/Python3 mixup as this branch was being moved to Python3 only at the time. 
At this point, if you want something that is stable, I would recommend you run the latest Python2 release which is here:
https://github.com/ARTFL-Project/PhiloLogic4/releases/tag/v4.5

Otherwise, if you want to be on the latest code (which is not guaranteed to be super stable), I've just released a beta2 version of the 4.6 release which is in Python3 only:
https://github.com/ARTFL-Project/PhiloLogic4/releases/tag/v4.6-beta.2

Depending on the size of your database, you may run into issues with OS X (running out of file descriptors at load time), and possibly some odd results given that OS X does not use GNU grep but BSD grep.

**Comment by AlexandreGefen** [comment]
Hi Clovis, 

No problem. I’ll try your solution on my OS X laptop.

Actually, on my two Ubuntu boxes, my main problem is I have to stick to Philologic 4.1, as 4.5 or 4.6 can not load any of my TEI corpus successfully, I don’t no why,
Best
Alexandre

**Comment by clovis** [comment]
Hi Alexandre,

Would you be able to send me a file that doesn't load successfully? The 4.5 and 4.6 parser is far more fault tolerant so this shouldn't happen. Thanks!

**Comment by AlexandreGefen** [comment]
See my opened issues on 4.6 errors

**Comment by AlexandreGefen** [comment]
Still any solution to the Macosx / 4.5 problem ?
The 4.1 works perfectly but the latest 4.5 not :

but I have got the same error :

MacBook-Pro-13-de-Alexandre:PhiloLogic4.5 alexandregefen$ philoload4 discours -c 2 /Users/alexandregefen/Documents/DH/Corpus/Académie/Discours/TEI/*.xml 
Traceback (most recent call last):
  File "/usr/local/bin/philoload4", line 9, in <module>
    from philologic.LoadOptions import LoadOptions
  File "/Library/Python/2.7/site-packages/philologic/__init__.py", line 5, in <module>
    from .DB import DB
  File "/Library/Python/2.7/site-packages/philologic/DB.py", line 5, in <module>
    from .Config import Config, db_locals_defaults, db_locals_header
  File "/Library/Python/2.7/site-packages/philologic/Config.py", line 7, in <module>
    from philologic.utils import pretty_print
  File "/Library/Python/2.7/site-packages/philologic/utils/__init__.py", line 5, in <module>
    from .convert_entities import convert_entities
  File "/Library/Python/2.7/site-packages/philologic/utils/convert_entities.py", line 4, in <module>
    import six.moves.html_entities
ImportError: No module named html_entities

NB pip freeze shows that the modules are installed :

htmlentities==0.2.1
namedentities==1.9.4

**Comment by clovis** [comment]
It looks like you may be missing the six module. 

Note that we don't support MacOS anymore given the constant issues we have with that platform. So I'd really recommend running PhiloLogic under Linux.

**Comment by AlexandreGefen** [comment]
I understand,  everything fine on our Ubuntu box, but having a local philologic on our Mac is really, really helpful for us.

Six is installed : 
six==1.4.1

Any hint ?

**Comment by clovis** [comment]
Yes, the six version you have is too old. OSX will not let you upgrade via pip. You want to download 1.10 and install manually by running:
`sudo python setup.py install`
You've just into one of the many annoyances we've had with OSX :-)

**Comment by AlexandreGefen** [comment]
Yes it works ! thanks a lot

**Comment by clovis** [comment]
great!
