### ISSUE TITLE
Arguments list too long

### ISSUE THREAD

**Issue by AlexandreGefen** [ARTFL-Project/PhiloLogic4#537]
Hello, I'm running latest stable Philologic on an Ubuntu box (standard kernel) and I have the famous and dreaded "Arguments list too long" for by biggest corpora (the smallest load ok), I think it should be easy too fix to batch command that loads the files,
best,
Alexandre

**Comment by AlexandreGefen** [comment]
Same probleme on my Macbook, big corpora don't load but smaller one are ok : 

MacBook-Pro-de-Alexandre:PhiloLogic4-4.6-beta.2 alexandregefen$ philoload4 fabula -c 2 /Users/alexandregefen/TEIFabula/*.xml 
-bash: /usr/local/bin/philoload4: Argument list too long

BUT :

MacBook-Pro-de-Alexandre:PhiloLogic4-4.6-beta.2 alexandregefen$ philoload4 fabula -c 2 /Users/alexandregefen/Documents/DH/Corpus/Académie/Discours/TEI/*.xml 

Copying files to database directory... done.
[...]

**Comment by clovis** [comment]
Yeah, the problem is because bash cannot list that many files at once. It's a hard-coded limit. The workaround is to use the -F flag to specify a file containing the filepaths for each file you want to load (one file per line). Note that files will be loaded in the order you provide in the file.
