### ISSUE TITLE
4.6 beta on my Mac errors 

### ISSUE THREAD

**Issue by AlexandreGefen** [ARTFL-Project/PhiloLogic4#538]
**Installed the 4.6 beta on my High Sierra Macbook, files load but with this repeated error**

Sat Aug  5 18:17:32 2017: Merging words in batches of 500...
/bin/bash: cannot make pipe for process substitution: Too many open files

**and after any errors like** 

gunzip: discours-de-reception-de-honore-armand-de-villars.xml.words.sorted.gz: uncompress failed

**at the end** 

### Finishing up ###
wrote database info to /Library/WebServer/Documents/philologic4/critique/data/db.locals.py.
wrote Web application info to /Library/WebServer/Documents/philologic4/critique/data/web_config.cfg.
sh: /bin/rm: Argument list too long
Application viewable at http://localhost/philologic4/critique

**when running the web site I have got these errors :**

[Sat Aug 05 18:26:18.335320 2017] [cgi:error] [pid 678] [client ::1:59188] AH01215: env: python3: No such file or directory: /Library/WebServer/Documents/philologic4/critique/dispatcher.py
[Sat Aug 05 18:26:18.335563 2017] [cgi:error] [pid 678] [client ::1:59188] End of script output before headers: dispatcher.py

**Comment by clovis** [comment]
This release has been cancelled. It's based off Python3 and will be called PhiloLogic5. It's been moved to a new repo: https://github.com/ARTFL-Project/PhiloLogic5
You probably shouldn't be using it right now as it isn't really tested, and will see extensive changes and breakage in the future.
