### ISSUE TITLE
problem with a tei file import

### ISSUE THREAD

**Issue by LaMOP** [ARTFL-Project/PhiloLogic4#540]
Hi
i tried to import a tei file but unfortunately without success so far.
The title appears but not the text. 
There are my logs. 
Any suggestions welcome on how these problems could be solved !!!!

*******philoload log
{
	'words_to_index': set([]),
	'post_filters': [
		<function word_frequencies at 0x7efffa44bc80>,
		<function normalized_word_frequencies at 0x7efffa44bcf8>,
		<function metadata_frequencies at 0x7efffa44bd70>,
		<function normalized_metadata_frequencies at 0x7efffa44bde8>
	],
	'file_type': 'xml',
	'plain_text_obj': [],
	'navigable_objects': (
		'doc',
		'div1',
		'div2',
		'div3',
		'para'
	),
	'break_apost': True,
	'long_word_limit': 200,
	'header': 'tei',
	'load_config': '',
	'sort_order': [
		'year',
		'author',
		'title',
		'filename'
	],
	'file_list': False,
	'web_app_dir': '/var/www/html/',
	'flatten_ligatures': True,
	'bibliography': '',
	'destination': './',
	'default_object_level': 'doc',
	'theme': '/var/lib/philologic4/web_app/app/assets/css/split/default_theme.css',
	'tag_to_obj_map': {
		'note': 'para',
		'argument': 'para',
		'postscript': 'para',
		'ab': 'line',
		'div3': 'div',
		'div2': 'div',
		'div1': 'div',
		'hyperdiv': 'div',
		'closer': 'para',
		'lg': 'para',
		'pb': 'page',
		'add': 'para',
		'opener': 'para',
		'ref': 'ref',
		'castlist': 'para',
		'front': 'div',
		'stage': 'para',
		'graphic': 'graphic',
		'sp': 'para',
		'list': 'para',
		'l': 'line',
		'q': 'para',
		'p': 'para',
		'epigraph': 'para',
		'div': 'div'
	},
	'files': [
		'/media/clu6.4497.tei'
	],
	'doc_xpaths': {
		'pub_place': [
			'.//sourceDesc/bibl/imprint/pubPlace',
			'.//sourceDesc/biblFull/publicationStmt/pubPlace',
			'.//sourceDesc/biblStruct/monog/imprint/pubPlace',
			'.//sourceDesc/bibl/pubPlace',
			'.//sourceDesc/bibl/publicationStmt/pubPlace'
		],
		'publisher': [
			".//sourceDesc/bibl/imprint[@type='artfl']",
			".//sourceDesc/bibl/imprint[@type='marc534']",
			'.//sourceDesc/bibl/imprint/publisher',
			'.//sourceDesc/biblStruct/monogr/imprint/publisher/name',
			'.//sourceDesc/biblFull/publicationStmt/publisher',
			'.//sourceDesc/bibl/publicationStmt/publisher',
			'.//sourceDesc/bibl/publisher',
			'.//publicationStmt/publisher',
			'.//publicationStmp'
		],
		'create_date': [
			'.//profileDesc/creation/date',
			'.//fileDesc/sourceDesc/bibl/imprint/date',
			'.//sourceDesc/biblFull/publicationStmt/date',
			'.//profileDesc/dummy/creation/date',
			'.//fileDesc/sourceDesc/bibl/creation/date'
		],
		'auth_gender': [
			'.//publicationStmt/notesStmt/note'
		],
		'language': [
			'.//profileDesc/language/language'
		],
		'author': [
			".//sourceDesc/bibl/author[@type='marc100']",
			".//sourceDesc/bibl/author[@type='artfl']",
			'.//sourceDesc/bibl/author',
			'.//titleStmt/author',
			'.//sourceDesc/biblStruct/monogr/author/name',
			'.//sourceDesc/biblFull/titleStmt/author',
			'.//sourceDesc/biblFull/titleStmt/respStmt/name',
			'.//sourceDesc/biblFull/titleStmt/author',
			'.//sourceDesc/bibl/titleStmt/author'
		],
		'notes': [
			'.//fileDesc/notesStmt/note',
			'.//publicationStmt/notesStmt/note'
		],
		'title': [
			".//sourceDesc/bibl/title[@type='marc245']",
			".//sourceDesc/bibl/title[@type='artfl']",
			'.//sourceDesc/bibl/title',
			'.//titleStmt/title',
			'.//sourceDesc/bibl/titleStmt/title',
			'.//sourceDesc/biblStruct/monogr/title',
			'.//sourceDesc/biblFull/titleStmt/title'
		],
		'period': [
			".//profileDesc/textClass/keywords[@scheme='period']/list/item",
			'.//SourceDesc/period',
			'.//sourceDesc/period'
		],
		'collection': [
			'.//seriesStmt/title'
		],
		'author_dates': [
			'.//sourceDesc/bibl/author/date',
			'.//titlestmt/author/date'
		],
		'idno': [
			'.//publicationStmt/idno/',
			'.//seriesStmt/idno/'
		],
		'text_form': [
			".//profileDesc/textClass/keywords[@scheme='form']/term"
		],
		'editor': [
			'.//sourceDesc/bibl/editor',
			'.//sourceDesc/biblFull/titleStmt/editor',
			'.//sourceDesc/bibl/title/Stmt/editor'
		],
		'extent': [
			'.//sourceDesc/bibl/extent',
			'.//sourceDesc/biblStruct/monog//extent',
			'.//sourceDesc/biblFull/extent'
		],
		'keywords': [
			'.//profileDesc/textClass/keywords/list/item'
		],
		'pub_date': [
			'.//sourceDesc/bibl/imprint/date',
			'.//sourceDesc/biblStruct/monog/imprint/date',
			'.//sourceDesc/biblFull/publicationStmt/date',
			'.//sourceDesc/bibFull/imprint/date',
			'.//sourceDesc/bibl/date',
			'.//text/front/docImprint/acheveImprime'
		],
		'structure': [
			'.//SourceDesc/structure',
			'.//sourceDesc/structure'
		],
		'text_genre': [
			".//profileDesc/textClass/keywords[@scheme='genre']/term",
			'.//SourceDesc/genre'
		]
	},
	'load_filters': [
		<function normalize_unicode_raw_words at 0x7efffa454b18>,
		<function make_word_counts at 0x7efffa454c08>,
		<function generate_words_sorted at 0x7efffa454c80>,
		<function inner_make_object_ancestors at 0x7efffa463c80>,
		<function sorted_toms at 0x7efffa1fc398>,
		<function inner_prev_next_obj at 0x7efffa1fc410>,
		<function generate_pages at 0x7efffa462c80>,
		<function prev_next_page at 0x7efffa462cf8>,
		<function generate_refs at 0x7efffa462d70>,
		<function generate_graphics at 0x7efffa462de8>,
		<function generate_lines at 0x7efffa462e60>,
		<function make_max_id at 0x7efffa462ed8>,
		<function store_words_and_philo_ids at 0x7efffa4631b8>
	],
	'suppress_tags': [],
	'db_destination': '/var/www/html/cbma',
	'token_regex': "[\\&A-Za-z0-9\\177-\\377][\\&A-Za-z0-9\\177-\\377\\_\\';]*",
	'pseudo_empty_tags': [],
	'sentence_breakers': [],
	'chars_not_to_index': '\\[\\{\\]\\}',
	'dbname': 'cbma',
	'break_sent_in_line_group': False,
	'database_root': '/var/www/html/',
	'abbrev_expand': True,
	'data_destination': '/var/www/html/cbma/data',
	'metadata_to_parse': {
		'graphic': [
			'facs'
		],
		'para': [
			'who',
			'resp',
			'id'
		],
		'page': [
			'n',
			'id',
			'facs'
		],
		'line': [
			'n',
			'id'
		],
		'ref': [
			'target',
			'n',
			'type'
		],
		'div': [
			'head',
			'type',
			'n',
			'id',
			'vol'
		]
	},
	'tag_exceptions': [
		'<hi[^>]*>',
		'<emph[^>]*>',
		'<\\/hi>',
		'<\\/emph>',
		'<orig[^>]*>',
		'<\\/orig>',
		'<sic[^>]*>',
		'<\\/sic>',
		'<abbr[^>]*>',
		'<\\/abbr>',
		'<i>',
		'</i>',
		'<sup>',
		'</sup>'
	],
	'join_hyphen_in_words': True,
	'force_delete': True,
	'debug': True,
	'cores': 2,
	'parser_factory': <class 'philologic.NewParser.XMLParser'>
}
cp: cannot copy a directory, '/var/www/html/cbma', into itself, '/var/www/html/cbma/cbma'

Copying files to database directory... done.

### Parsing metadata ###
Wed Dec 13 14:02:59 2017: Parsing metadata in 1 files...
parsing clu6.4497.tei header...
{
	'publisher': '??',
	'create_date': '1215',
	'author': 'AB  (abbaye, prieure, abbe, moine)      Cluny (Saint-Pierre et Saint-Paul)      \n',
	'title': "Titre Edition =  ; Analyse Edition = PARVUS ROTULUS SPECTANS, UT VIDETUR, AD INQUISITIONEM FACTAM DE JURIBUS ABBATIS CLUNIACENSIS IN PRIORATUM CARITATIS. ; Analyse CBMA = Texte d\xc3\xa9finissant les relations entre l'abb\xc3\xa9 de Cluny et l'abbaye de La Charit\xc3\xa9. ; Edition = BERNARD A., BRUEL A., Recueil des chartes de l'abbaye de Cluny. Tome 6 : 1211-1300, Paris, Imprimerie nationale, 1903, p. 49-54, n\xc2\xb0 4497.",
	'collection': 'Recueil des chartes de l abbaye de Cluny. Tome 6 : 1211-1300',
	'filename': 'clu6.4497.tei',
	'editor': 'Auguste Bernard et Alexandre Bruel',
	'year': '1215',
	'pub_date': '1215, environ.'
}
Wed Dec 13 14:02:59 2017: Sorting files by the following metadata fields: year, author, title, filename... 

### Parsing files ###
Wed Dec 13 14:02:59 2017: parsing 1 files.
Wed Dec 13 14:02:59 2017: parsing 1 : clu6.4497.tei
Wed Dec 13 14:03:00 2017: done parsing

### Merge parser output ###
Wed Dec 13 14:03:00 2017: sorting words
Wed Dec 13 14:03:00 2017: Merging words in batches of 500...
Wed Dec 13 14:03:00 2017: 1 files merged...
Wed Dec 13 14:03:00 2017: word sort returned 0
Wed Dec 13 14:03:00 2017: concatenating document-order words file... done
Wed Dec 13 14:03:00 2017: sorting objects
Wed Dec 13 14:03:00 2017: Merging toms in batches of 500...
Wed Dec 13 14:03:00 2017: 1 files merged...
Wed Dec 13 14:03:00 2017: object sort returned 0
Wed Dec 13 14:03:00 2017: joining pages
Wed Dec 13 14:03:00 2017: joining references
Wed Dec 13 14:03:00 2017: joining graphics
Wed Dec 13 14:03:00 2017: joining lines

### Create inverted index ###
[1, 1, 1, 1, 3, 245, 57, 13872, 1]
[1, 1, 1, 1, 2, 8, 6, 14, 1]
35 bits wide.
freq1: 10; 4 bits
freq2: 154; 8 bits
offst: 43008; 16 bits
Wed Dec 13 14:03:00 2017: analysis done
reading dbspecs in from /var/www/html/cbma/data/WORK/dbspecs4.h...
done. 1571 hits packed in 503 entries.
Wed Dec 13 14:03:00 2017: all indices built. moving into place.

### Post-processing filters ###
Wed Dec 13 14:03:00 2017: Loading the words SQLite table...
Wed Dec 13 14:03:00 2017: Loading the lines SQLite table...
Wed Dec 13 14:03:00 2017: Loading the graphics SQLite table...
Wed Dec 13 14:03:00 2017: Loading the refs SQLite table...
Wed Dec 13 14:03:00 2017: Loading the pages SQLite table...
Wed Dec 13 14:03:00 2017: Loading the toms SQLite table...
Wed Dec 13 14:03:00 2017: Generating word frequencies...
Wed Dec 13 14:03:00 2017: Generating normalized word frequencies...
Wed Dec 13 14:03:00 2017: Generating metadata frequencies...
The following fields were not found in the input corpus options, facs, who, resp, id, type, vol
Wed Dec 13 14:03:00 2017: Generating normalized metadata frequencies...

### Finishing up ###
wrote database info to /var/www/html/cbma/data/db.locals.py.
wrote Web application info to /var/www/html/cbma/data/web_config.cfg.
Application viewable at http://philologic.lamop.fr/cbma

[clu6.4497.txt](https://github.com/ARTFL-Project/PhiloLogic4/files/1555798/clu6.4497.txt)

*** philologic test web site
http://philologic.lamop.fr/cbma/

**Comment by clovis** [comment]
What version of PhiloLogic4 are you using? I ask because I was able to load your file, search and display text without issue. You can find the latest release here:
https://github.com/ARTFL-Project/PhiloLogic4/releases/

Otherwise, I see that you have missing quotes in one of your attributes in the sample file you sent which is invalid in XML:
<div1 n=4497> should be <div1 n="4497">
PhiloLogic also only really supports parsing attributes with double quotes (to avoid problems with apostrophes)

I hope that helps.

**Comment by LaMOP** [comment]
PhiloLogic4-4.5.4.tar.gz :-(
i check with the new version.
Thanks !!!!

**Comment by LaMOP** [comment]
It's ok with the last version !!!
Thanks !!!
