### ISSUE TITLE
Add option to bypass table of contents and go straight to the text

### ISSUE THREAD

**Issue by LaMOP** [ARTFL-Project/PhiloLogic4#541]
Hi
We got a corpus with a lot of simple texts
How to avoid table of contents step, because of our texts got only single page.
Best Regards

**Comment by clovis** [comment]
This is not possible in the current version. We may add an option to bypass the table of contents in PhiloLogic4, but most likely this will happen in PhiloLogic5 (the Python3 version). I'll keep this open in case we find time to make the change.

**Comment by clovis** [comment]
I've just updated the code to support your use case. You will need to reload your database however. ONce that is done, go to the web_config.cfg file, and change the `skip_table_of_contents` variable to `True`. Let me know if this doesn't work for you. Thanks!

**Comment by clovis** [comment]
You'll want to install the latest version available here:
https://github.com/ARTFL-Project/PhiloLogic4/releases/tag/v4.5.6

**Comment by LaMOP** [comment]
Thanks a lot for your update !!!!!!

Best regards

pierre brochard


Le 04/04/2018 à 18:16, Clovis Gladstone a écrit :
