### ISSUE TITLE
How to disable the header's display

### ISSUE THREAD

**Issue by LaMOP** [ARTFL-Project/PhiloLogic4#544]
Hi
is it possible to disable the header's diplay (span=xml-TeiHeader)
It's difficult to do the differences immediatly between the text and the metadata.
Our examples:
 
_Saône-et-Loire Agrafe : Daniel et les lions Mâcon 9999 collection de Madame Le Fèvre 46.306666666667,4.8319444444444 note   Q174247
latin CBMA 9999_macon_SL222
Daniel profeta. Abbacu profeta._

**Comment by clovis** [comment]
Fixed in PhiloLogic 4.7
